2024-11-11 10:47:21,878 - SistemaNF - ERROR - Erro em Teste Local:
Tipo: UnboundLocalError
Mensagem: cannot access local variable 'xml_teste' where it is not associated with a value
Traceback: Traceback (most recent call last):
  File "c:\Users\VAS MTZ\Desktop\Caetano Apollo\automaticNF\processar_xml.py", line 35, in testar_processamento_local
    print(f"Arquivo de teste não encontrado: {xml_teste}")
                                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'xml_teste' where it is not associated with a value

2024-11-11 10:47:21,878 - SistemaNF - ERROR - Erro em Teste Local:
Tipo: UnboundLocalError
Mensagem: cannot access local variable 'xml_teste' where it is not associated with a value
Traceback: Traceback (most recent call last):
  File "c:\Users\VAS MTZ\Desktop\Caetano Apollo\automaticNF\processar_xml.py", line 35, in testar_processamento_local
    print(f"Arquivo de teste não encontrado: {xml_teste}")
                                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'xml_teste' where it is not associated with a value

